### ISSUE TITLE
Rails 4.2 support

### ISSUE THREAD

**Issue by aamine** [aamine/activerecord4-redshift-adapter#14]
I confirmed that this driver does not work with Rails 4.2.  Optinons are:

1. Import PostgreSQL adapter 4.1 -> 4.2 difference.  Abount 3000 lines change.
2. Copy whole PostgreSQL adapter 4.2 and modify it (apply current diffs again).  About 600 lines change.

Apparently option 2. is better.  My commercial system rely on this adapter, I try it in weeks.

**Comment by hirakiuc** [comment]
+1

**Comment by ook** [comment]
Option 2 make more sense.

**Comment by epantera** [comment]
thanks

**Comment by amassaad** [comment]
What is the issue with 4.2, any progress on your solution @aamine 

Thanks :smile_cat:

**Comment by aamine** [comment]
Now Rails 4.2 is supported by version 0.2, close.
