### ISSUE TITLE
Migrations with distkey or sortkey

### ISSUE THREAD

**Issue by lorgio** [aamine/activerecord4-redshift-adapter#21]
Currently I've been running migrations with SQL written by hand.  I've looked through the code and tests, but see no references to distkey or sortkey or any way to be able to add it upon creation.  If someone can point to me to the right direction, I could help implement this feature if it is not already done.

**Comment by ook** [comment]
I pass these informations as options:

**Comment by ook** [comment]
I pass these informations as options:

```
    create_table :my_table, id: false, options: 'SORTKEY (col_sort_1, col_sort_2)' do |t|
        t.column :id, "character varying(70) ENCODE LZO NOT NULL PRIMARY KEY"
        t.column :numeric_field, "integer ENCODE BYTEDICT NOT NULL"
        t.column :my_interesting_id, "character varying(34) ENCODE LZO DISTKEY NOT NULL"
    end
```

**Comment by lorgio** [comment]
![](http://i.imgur.com/7eAVx.gif)

Here goes to re-writing my migrations
