### ISSUE TITLE
Hosting on rubygems

### ISSUE THREAD

**Issue by realdoug** [aamine/activerecord4-redshift-adapter#8]
Hi-

Thanks for writing this.  Is there any way you could host it on rubygems?  Would you mind if I did so?

Thanks
Doug

**Comment by aamine** [comment]
Now I push activerecord4-redshift-adapter gem.  You can get it from RubyGems.org !!
https://rubygems.org/gems/activerecord4-redshift-adapter

**Comment by realdoug** [comment]
awesome!
